### PR TITLE
[ADD] blog post for inlets.dev

### PR DESCRIPTION
**Pull request by markopolo123**
Proposed blog post for inlets.

Signed-off-by: Mark Sharpley

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @markopolo123, I sent you some feedback via email. Let me know when you've had time to push that?

Regards,

Alex

**Review by alexellis — CHANGES_REQUESTED** [review]
Review sent to author

**Comment by alexellis** [comment]
@markopolo123 it's been a couple of weeks since I left feedback, can you tell me when I should expect the changes so that I can review them again and potentially get your story published?

**Comment by markopolo123** [comment]
> @markopolo123 it's been a couple of weeks since I left feedback, can you tell me when I should expect the changes so that I can review them again and potentially get your story published?

Pushed changes, let me know if you require further changes. 
Best, 
Mark

**Comment by alexellis** [comment]
Just checked out the latest update, do you have an image of the Raspberry Pi, or the battery + kit?

**Comment by markopolo123** [comment]
> Just checked out the latest update, do you have an image of the Raspberry Pi, or the battery + kit?

Yeah, I can add some more pictures.

**Comment by alexellis** [comment]
I'm going to push a version of the blog post, then can you send a PR to add the pictures in JPG format? I think it would really add to the story :)

**Comment by alexellis** [comment]
Your post will be live at: https://inlets.dev/blog/2021/07/13/inlets-narrowboat.html

So, you can send a PR to master in a new/fresh branch and enrich the post. The date has also changed to `blog/_posts/2021-07-13-inlets-narrowboat.md`

**Pull request closed without merging**
