### PR TITLE
Boat update

### PR DESCRIPTION
**Pull request by markopolo123**
Adding pictures of the solar panel and batteries. Fixed a small typo

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for getting more pictures, I'm excited to see them on the post.

However, this appears to be adding a new blog post URL, when we already have one in the repo and it adds all the images a second time.

Was this from an old branch?

I would suggest deleting your fork, forking it again and creating a new branch, then edit the existing blog post.

**Comment by markopolo123** [comment]
Probably, I'll take a quick look later and update the PR

Mark

**Comment by alexellis** [comment]
@markopolo123 can you take a look this week please? :)

**Comment by alexellis** [comment]
I'm going to add the two new pictures myself, but feel free to send a PR to the existing markdown file if there are additions that we need. I couldn't see any in the diff.

**Pull request closed without merging**
